"""Consultant packet export: one command, full stakeholder deliverable directory.

A consultant packet bundles every artifact a client meeting needs into a
single directory:

    packet/
    ├── README.md                 — explains the contents
    ├── executive_snapshot.txt    — one-page plain-text summary
    ├── executive_snapshot.html   — same, as HTML
    ├── workflow_before.mmd       — Mermaid flowchart (before)
    ├── workflow_after.mmd        — Mermaid flowchart (after)
    ├── roi_waterfall.svg         — ROI decomposition chart
    ├── bottleneck_heatmap.svg    — node pressure heatmap
    ├── assumptions.json          — simulation parameters
    ├── kpi_summary.json          — structured KPI output
    └── recommendations.txt       — plain-text recommendations

No external dependencies.  All artifacts are plain text, JSON, SVG, or HTML.
"""

from __future__ import annotations

import json
from pathlib import Path

from b2b_workflow_simulator.assumptions import AssumptionProfile
from b2b_workflow_simulator.heatmap import build_bottleneck_heatmap, heatmap_to_svg
from b2b_workflow_simulator.kpi import KPIResult
from b2b_workflow_simulator.redesign import compare_workflows
from b2b_workflow_simulator.simulation import SimulationResult
from b2b_workflow_simulator.snapshot import build_snapshot, snapshot_to_html, snapshot_to_text
from b2b_workflow_simulator.visualization import to_mermaid
from b2b_workflow_simulator.waterfall import build_roi_waterfall, waterfall_to_svg
from b2b_workflow_simulator.workflow import Workflow


def _kpi_to_dict(kpi: KPIResult) -> dict:
    """Serialize a KPIResult to a plain JSON-serializable dict."""
    return {
        "workflow_name": kpi.workflow_name,
        "total_cases": kpi.total_cases,
        "completed_cases": kpi.completed_cases,
        "failed_cases": kpi.failed_cases,
        "completion_rate": round(kpi.completion_rate, 4),
        "failure_rate": round(kpi.failure_rate, 4),
        "total_cost": round(kpi.total_cost, 4),
        "avg_cost_per_case": round(kpi.avg_cost_per_case, 4),
        "avg_cycle_time_minutes": round(kpi.avg_cycle_time_minutes, 4),
        "avg_wait_time_minutes": round(kpi.avg_wait_time_minutes, 4),
        "escalation_rate": round(kpi.escalation_rate, 4),
        "total_escalations": kpi.total_escalations,
        "bottleneck_nodes": kpi.bottleneck_nodes(5),
    }


def _build_readme(
    example_name: str,
    before_wf: Workflow,
    after_wf: Workflow,
    profile: AssumptionProfile,
    before_kpi: KPIResult,
    after_kpi: KPIResult,
) -> str:
    diff = compare_workflows(before_kpi, after_kpi, profile.implementation_cost)
    cur = profile.currency_label
    lines: list[str] = [
        f"# Consultant Packet: {example_name}",
        "",
        "Generated by b2b-simulator.  All figures are directional simulation "
        "estimates — validate against real operational data before committing.",
        "",
        "## Files",
        "",
        "| File | Description |",
        "|---|---|",
        "| `executive_snapshot.txt` | One-page plain-text summary |",
        "| `executive_snapshot.html` | Same summary as HTML |",
        "| `workflow_before.mmd` | Mermaid flowchart — before (paste into mermaid.live) |",
        "| `workflow_after.mmd` | Mermaid flowchart — after |",
        "| `roi_waterfall.svg` | ROI decomposition chart |",
        "| `bottleneck_heatmap.svg` | Node pressure heatmap |",
        "| `assumptions.json` | Simulation parameters used |",
        "| `kpi_summary.json` | Structured KPI output |",
        "| `recommendations.txt` | Top recommendations |",
        "",
        "## Quick Summary",
        "",
        f"- **Workflows compared:** {before_wf.name} → {after_wf.name}",
        f"- **Cases simulated:** {profile.num_cases}",
        f"- **Seed:** {profile.seed}",
        f"- **Total cost savings:** {cur}{diff.roi.total_cost_savings:,.2f}",
        f"- **Completion rate:** {before_kpi.completion_rate:.1%} "
        f"→ {after_kpi.completion_rate:.1%}",
        f"- **Avg cycle time:** {before_kpi.avg_cycle_time_minutes:.1f} min → "
        f"{after_kpi.avg_cycle_time_minutes:.1f} min",
        "",
        "## Assumptions",
        "",
        f"- AI error rate multiplier: {profile.ai_error_rate_multiplier}× (1.0 = unchanged)",
        f"- AI cost multiplier: {profile.ai_cost_multiplier}× (1.0 = unchanged)",
        f"- Human hourly cost multiplier: "
        f"{profile.human_hourly_cost_multiplier}× (1.0 = unchanged)",
        "",
        "These multipliers are logged for transparency; the underlying workflow "
        "definitions were used as-is in this packet.",
        "",
        "## How to view Mermaid diagrams",
        "",
        "1. Open https://mermaid.live",
        "2. Paste the contents of `workflow_before.mmd` or `workflow_after.mmd`",
        "3. The flowchart renders in the right panel",
    ]
    return "\n".join(lines)


def _build_recommendations_txt(before_kpi: KPIResult, after_kpi: KPIResult) -> str:
    from b2b_workflow_simulator.redesign import compare_workflows
    from b2b_workflow_simulator.report import build_recommendation, build_risks

    diff = compare_workflows(before_kpi, after_kpi)
    risks = build_risks(diff)
    rec = build_recommendation(diff)
    lines: list[str] = [
        "RECOMMENDATIONS",
        "=" * 60,
        "",
        "Overall recommendation:",
        f"  {rec}",
        "",
        "Risk flags:",
    ]
    lines += [f"  - {r}" for r in risks]
    return "\n".join(lines)


def generate_packet(
    example_name: str,
    before_workflow: Workflow,
    after_workflow: Workflow,
    before_result: SimulationResult,
    after_result: SimulationResult,
    profile: AssumptionProfile,
    output_dir: Path,
) -> dict[str, Path]:
    """Generate all consultant packet files into ``output_dir``.

    Args:
        example_name: Short name used in headings.
        before_workflow: The "before" workflow definition.
        after_workflow: The "after" workflow definition.
        before_result: Simulation result for the "before" variant.
        after_result: Simulation result for the "after" variant.
        profile: ``AssumptionProfile`` used for the run.
        output_dir: Directory to write all files into.  Created if absent.

    Returns:
        A dict mapping filename → absolute ``Path`` for each file written.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    before_kpi = before_result.kpi
    after_kpi = after_result.kpi
    files: dict[str, Path] = {}

    def write(filename: str, content: str) -> Path:
        p = output_dir / filename
        p.write_text(content)
        files[filename] = p
        return p

    snapshot = build_snapshot(
        before_kpi, after_kpi,
        implementation_cost=profile.implementation_cost,
    )
    write("executive_snapshot.txt", snapshot_to_text(snapshot))
    write("executive_snapshot.html", snapshot_to_html(snapshot))

    write("workflow_before.mmd", to_mermaid(before_workflow))
    write("workflow_after.mmd", to_mermaid(after_workflow))

    waterfall = build_roi_waterfall(
        before_kpi, after_kpi,
        implementation_cost=profile.implementation_cost,
        currency=profile.currency_label,
    )
    write("roi_waterfall.svg", waterfall_to_svg(waterfall))

    heatmap = build_bottleneck_heatmap(after_workflow, after_kpi)
    write("bottleneck_heatmap.svg", heatmap_to_svg(heatmap))

    write("assumptions.json", json.dumps(profile.to_dict(), indent=2) + "\n")

    kpi_summary = {
        "before": _kpi_to_dict(before_kpi),
        "after": _kpi_to_dict(after_kpi),
    }
    write("kpi_summary.json", json.dumps(kpi_summary, indent=2) + "\n")

    write("recommendations.txt", _build_recommendations_txt(before_kpi, after_kpi))

    readme = _build_readme(
        example_name, before_workflow, after_workflow, profile, before_kpi, after_kpi
    )
    write("README.md", readme)

    return files


__all__ = [
    "generate_packet",
]
